### ISSUE TITLE
Maximum amount of Items?

### ISSUE THREAD

**Issue by iwemuiser** [scholarslab/NeatlineTime#55]
What is the maximum amount of items that can be plotted? We now want to visualize a subcollection of 17000 items, but nothing appears in the timeline after a few minutes of rendering.

**Comment by erochest** [comment]
There are two issues here, both complicated because we're trying to optimize for everyone else's computers, not ours. First is the performance of the search on the backend. Second is rendering all the points.

For the time being, let's just include a message if the search query returns too many items.

**Comment by erochest** [comment]
I do want to do some testing about this, particularly since we're swapping out the entire front end. As much as anything, I'd like to know how soon we can expect people to start complaining about this. 😉

**Comment by csbailey5t** [comment]
Timeline.js handled 100 items just fine. Once I got up to 300 items, it did take a noticeable few seconds to render.

**Comment by csbailey5t** [comment]
An alert is added on the admin view of the timeline for more than 100 items. It should be enough to encourage people to break up timelines if they go over that fairly stable amount of items. We can revise as needed if we start getting comments about it. See 78502a4eeb448b2963c0fc393c72d3cb19d560a8
